[package]
name = "performant"
version = "0.3.0"
edition = "2024"

[dependencies]
steady_state = { git = "ssh://git@github.com/kmf-lab/steady-state-stack.git", branch = "main" }
#steady_state = "0.3.0"

clap             = { version = "4.6", features = ["derive"] }

[profile.release]
opt-level = 3 # optimize for size 'z' speed 3
lto = true # link time optimization
codegen-units = 1 # only one codegen unit to reduce binary size
strip = 'symbols' # strip symbols